sudo: required
language: generic

# It installs docker on the machine
services: 
  - docker

# Series of command to run before we deploy a project or run a test
before_install:
  - docker build -t codetraxx/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true codetraxx/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-860984055984"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"